addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"          % "0.10.0")
addSbtPlugin("com.github.gseitz" % "sbt-release"            % "1.0.13")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"                % "1.0.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-license-report"     % "1.2.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"             % "5.6.0")
addSbtPlugin("org.scalastyle"    %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"          % "1.6.1")
addSbtPlugin("org.wartremover"   % "sbt-wartremover"        % "2.4.10")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"           % "2.4.2")

